repos:
-   repo: local
    hooks:
    - id: flake8
      entry: flake8
      name: flake8
      language: python
      types: [file, python]
    - id: black
      entry: black -v
      name: black
      language: python
      types: [file, python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: name-tests-test
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: mixed-line-ending
    - id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.2.0
    hooks:
    - id: reorder-python-imports
