language: python
dist: trusty
sudo: false

branches:
  only:
    - master

install:
  - pip install tox

script:
  - tox

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: required

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

notifications:
  email:
    on_success: never
